"use client";
import { useState } from "react";
import AuthGate, { useRimauLog } from "./auth-gate";

type View = "overview" | "students" | "sessions" | "report" | "tasks" | "notes";
const students = [
  {id:"nadia",name:"Nadia M.",email:"nadia@gmail.com",initials:"NM",week:1,stage:"Foundation",progress:4,next:"29 Aug 2026",status:"Active",attention:"Reflection submitted"},
  {id:"aisyah",name:"Aisyah R.",email:"aisyah@gmail.com",initials:"AR",week:3,stage:"Cloud fundamentals",progress:13,next:"30 Aug 2026",status:"Active",attention:"Assignment due soon"},
  {id:"farah",name:"Farah N.",email:"farah@gmail.com",initials:"FN",week:6,stage:"IAM & access",progress:25,next:"02 Sep 2026",status:"Active",attention:"No pending action"},
];
const competencies = [
  ["Cybersecurity fundamentals","Developing",45,"Understands core terms; needs stronger risk reasoning."],
  ["Cloud fundamentals","Beginner",25,"Starting with one AWS architecture at a time."],
  ["Technical communication","Developing",50,"Good questions; practise explaining without relying on commands."],
  ["Professional documentation","Beginner",20,"First GitHub-ready Markdown evidence is pending."],
] as const;
const nav:{id:View;label:string;icon:string}[]=[
  {id:"overview",label:"Overview",icon:"⌂"},{id:"students",label:"Students",icon:"♙"},{id:"sessions",label:"Sessions",icon:"◫"},{id:"report",label:"Report card",icon:"◎"},{id:"tasks",label:"Assignments",icon:"✓"},{id:"notes",label:"Markdown notes",icon:"#"}
];
export default function Home(){
 const [view,setView]=useState<View>("overview"); const [toast,setToast]=useState("");
 const [studentId,setStudentId]=useState("nadia"); const student=students.find(s=>s.id===studentId)??students[0];
 const [note,setNote]=useState("# Week 1 Reflection\n\n## What I learned\n- The difference between a threat, vulnerability and risk.\n- Why cloud security starts with understanding the architecture.\n\n## What I still need to understand\n- How IAM roles work in a real AWS environment.\n\n## My next action\nMap a simple AWS workload before the next session.");
 const [preview,setPreview]=useState(false); const notify=(m:string)=>{setToast(m);setTimeout(()=>setToast(""),2000)};
 const download=()=>{const u=URL.createObjectURL(new Blob([note],{type:"text/markdown"}));const a=document.createElement("a");a.href=u;a.download="week-01-reflection.md";a.click();URL.revokeObjectURL(u);notify("Markdown downloaded")};
 return <AuthGate><main className="shell"><aside><div className="brand"><b>R</b><div><strong>RimauLog</strong><small>Log progress. Build capability.</small></div></div><nav>{nav.map(n=><button className={view===n.id?"on":""} onClick={()=>setView(n.id)} key={n.id}><span>{n.icon}</span>{n.label}{n.id==="students"&&<em>{students.length}</em>}</button>)}</nav><div className="program"><small>SELECTED STUDENT</small><strong>{student.name} · Week {student.week}</strong><i><b style={{width:`${student.progress}%`}}/></i><span>{student.stage}</span></div><div className="me"><b>AK</b><div><strong>Adani Kamal</strong><small>Mentor · Admin</small></div></div></aside><section className="work"><header><div><small>MENTORING WORKSPACE</small><h1>{nav.find(n=>n.id===view)?.label}</h1></div><div className="header-tools"><label>Viewing <select value={studentId} onChange={e=>setStudentId(e.target.value)}>{students.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label><button onClick={()=>notify("New session draft created")}>＋ New session</button></div></header>
 {view==="overview"&&<Overview go={setView} notify={notify} student={student}/>} {view==="students"&&<Students selected={studentId} choose={id=>{setStudentId(id);setView("overview")}} notify={notify}/>} {view==="sessions"&&<Sessions notify={notify}/>} {view==="report"&&<Report/>} {view==="tasks"&&<Tasks notify={notify}/>} {view==="notes"&&<Notes note={note} setNote={setNote} preview={preview} setPreview={setPreview} download={download} notify={notify}/>}</section>{toast&&<div className="toast">✓ {toast}</div>}</main></AuthGate>
}
function Overview({go,notify,student}:{go:(v:View)=>void;notify:(m:string)=>void;student:typeof students[number]}){return <div className="page"><section className="welcome"><div><small>Saturday, 22 August 2026 · {student.name}</small><h2>Good morning, Dani.</h2><p>{student.attention}. Here’s what needs your attention for this student.</p></div><div className="journey"><b>{student.progress}%</b><div><small>JOURNEY PROGRESS</small><strong>{student.week} of 24 weeks</strong><span>{student.stage}</span></div></div></section><div className="stats"><Stat icon="✓" label="TASKS COMPLETED" value="1" detail="/ 3 this week"/><Stat icon="◫" label="SESSIONS HELD" value={String(student.week)} detail="/ 24 total"/><Stat icon="↗" label="SKILLS DEVELOPING" value="4" detail="competencies"/></div><div className="grid"><section className="card focus"><div className="head"><div><small>CURRENT FOCUS</small><h3>Build the foundation first</h3></div><em>Week {student.week}</em></div><p>One architecture, one task flow, and clear reasoning behind every security decision.</p>{[["✓","Baseline conversation","Completed during Session 01"],["2","Map one AWS workload","Due 28 August · In progress"],["3","Explain the risk locations","Not started"]].map(x=><div className="step" key={x[1]}><b>{x[0]}</b><div><strong>{x[1]}</strong><small>{x[2]}</small></div></div>)}<button className="link" onClick={()=>go("tasks")}>View assignment →</button></section><section className="card next"><div className="head"><div><small>NEXT SESSION</small><h3>Cloud Building Blocks</h3></div><b className="date">29<small>AUG</small></b></div><p>Trace one AWS implementation from user request to stored data—and find where security matters.</p><div className="meta">◷ 10:00 AM　 ◫ 60 minutes</div><button className="soft" onClick={()=>notify("Session agenda opened")}>Open session agenda</button></section><section className="card"><div className="head"><h3>Recent activity</h3><button className="link" onClick={()=>go("sessions")}>View all</button></div><div className="activity"><b>{student.initials}</b><div><strong>{student.name} submitted an update</strong><p>{student.attention}</p><small>18 minutes ago</small></div></div><div className="activity"><b>✓</b><div><strong>Latest session marked complete</strong><p>{student.stage}</p><small>Today, 11:24 AM</small></div></div></section><section className="card"><div className="head"><h3>Competency pulse</h3><button className="link" onClick={()=>go("report")}>Full report</button></div>{competencies.slice(0,3).map(c=><div className="pulse" key={c[0]}><div><span>{c[0]}</span><small>{c[1]}</small></div><i><b style={{width:`${c[2]}%`}}/></i></div>)}</section></div></div>}
function Students({selected,choose,notify}:{selected:string;choose:(id:string)=>void;notify:(m:string)=>void}){return <div className="page"><Intro title="Students" text="Manage every mentoring journey separately while keeping one clear overview."><button onClick={()=>notify("Student invitation form opened")}>＋ Invite student</button></Intro><div className="student-summary"><Stat icon="♙" label="ACTIVE STUDENTS" value={String(students.length)} detail="in mentorship"/><Stat icon="◫" label="SESSIONS THIS WEEK" value="3" detail="across students"/><Stat icon="!" label="NEEDS ATTENTION" value="2" detail="student updates"/></div><section className="student-list"><div className="student-list-head"><span>Student</span><span>Journey</span><span>Next session</span><span>Attention</span><span></span></div>{students.map(s=><article className={selected===s.id?"selected":""} key={s.id}><div className="student-person"><b>{s.initials}</b><div><strong>{s.name}</strong><small>{s.email}</small></div></div><div className="student-progress"><span>Week {s.week} · {s.stage}</span><i><b style={{width:`${s.progress}%`}}/></i></div><span>{s.next}</span><em>{s.attention}</em><button className="soft" onClick={()=>choose(s.id)}>{selected===s.id?"Viewing":"Open profile"}</button></article>)}</section></div>}
function Stat({icon,label,value,detail}:{icon:string;label:string;value:string;detail:string}){return <article><b>{icon}</b><div><small>{label}</small><strong>{value} <em>{detail}</em></strong></div></article>}
function Intro({title,text,children}:{title:string;text:string;children?:React.ReactNode}){return <div className="intro"><div><h2>{title}</h2><p>{text}</p></div>{children}</div>}
function Sessions({notify}:{notify:(m:string)=>void}){const data=[["01","Foundation & Direction","22 Aug 2026","Completed","Baseline discussion, goals, learning style and six-month direction."],["02","Cloud Building Blocks","29 Aug 2026","Upcoming","Trace one AWS workload and explain where identity, network and data risks live."],["03","Identity & Least Privilege","05 Sep 2026","Planned","IAM users, roles, policies and practical least-privilege reasoning."]];return <div className="page"><Intro title="Weekly mentoring record" text="Every conversation becomes a clear trail of learning, evidence and next actions."/><div className="list">{data.map(s=><article key={s[0]}><b>{s[0]}</b><div><h3>{s[1]} <em>{s[3]}</em></h3><p>{s[4]}</p><small>{s[2]}</small></div><button className="link" onClick={()=>notify(`${s[1]} opened`)}>Open →</button></article>)}</div></div>}
function Report(){return <div className="page"><Intro title="Growth report card" text="Progress is measured through demonstrated understanding—not arbitrary marks."/><section className="card report">{competencies.map(c=><div key={c[0]}><span>{c[1]}</span><h3>{c[0]}</h3><p>{c[3]}</p><i><b style={{width:`${c[2]}%`}}/></i><small>{c[2]}% toward independent practice</small></div>)}</section></div>}
function Tasks({notify}:{notify:(m:string)=>void}){const data=[["Cloud","Map one AWS architecture","28 Aug","In progress"],["Reflection","Write Week 1 reflection","24 Aug","Submitted"],["Portfolio","Create mentoring GitHub repository","25 Aug","Not started"]];return <div className="page"><Intro title="Assignments & evidence" text="Small, purposeful tasks that turn learning into portfolio proof."><button onClick={()=>notify("Assignment draft created")}>＋ Add assignment</button></Intro><div className="tasks">{data.map(t=><article className="card" key={t[1]}><div><em>{t[0]}</em><span>{t[3]}</span></div><h3>{t[1]}</h3><p>Due {t[2]} · Evidence required</p><button className="soft" onClick={()=>notify(`${t[1]} opened`)}>View details</button></article>)}</div></div>}
function Notes({note,setNote,preview,setPreview,download,notify}:{note:string;setNote:(v:string)=>void;preview:boolean;setPreview:(v:boolean)=>void;download:()=>void;notify:(m:string)=>void}){
 const client=useRimauLog(); const [saving,setSaving]=useState(false);
 async function save(){
  if(!client){notify("Demo note saved for this session");return}
  setSaving(true); const {data}=await client.auth.getUser();
  if(!data.user){notify("Please sign in again");setSaving(false);return}
  const {error}=await client.from("notes").upsert({author_id:data.user.id,mentee_id:data.user.id,title:"Week 1 Reflection",body_markdown:note,updated_at:new Date().toISOString()},{onConflict:"author_id,title"});
  notify(error?`Could not save: ${error.message}`:"Note saved securely"); setSaving(false);
 }
 return <div className="page"><Intro title="Markdown learning notes" text="Write once, download as .md, and publish the evidence to GitHub."><div className="actions"><button className="soft" onClick={download}>↓ Download .md</button><button disabled={saving} onClick={save}>{saving?"Saving…":"Save note"}</button></div></Intro><section className="card editor"><div><button className={!preview?"sel":""} onClick={()=>setPreview(false)}>Write</button><button className={preview?"sel":""} onClick={()=>setPreview(true)}>Preview</button><span>week-01-reflection.md</span></div>{preview?<section>{note.split("\n").map((x,i)=>x.startsWith("# ")?<h1 key={i}>{x.slice(2)}</h1>:x.startsWith("## ")?<h2 key={i}>{x.slice(3)}</h2>:x.startsWith("- ")?<li key={i}>{x.slice(2)}</li>:<p key={i}>{x||" "}</p>)}</section>:<textarea value={note} onChange={e=>setNote(e.target.value)} aria-label="Markdown note editor"/>}</section></div>
}
